import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";
import CaseDetailHeader from "@/components/CaseDetail/header";
import CaseOverview from "@/components/CaseDetail/overview";
import CaseParagraph from '@/components/CaseDetail/paragraph';
import Main from "@/components/Layout/main";
import { caseDetail } from "@/data/cases";

export default function CaseDetail() {
  return (
    <>
      <Head>
        <title>Ingsist CaseDetail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />

        <CaseDetailHeader title={caseDetail.name} year={caseDetail.year} />
        <Main>
          <CaseOverview overview={caseDetail.overview} />

          {
            caseDetail.paragraph.map((d, i) => (
              <CaseParagraph key={d.title} block={d} index={i + 2}/>
            ))
          }
        </Main>
      </div>
    </>
  );
}
