import Head from 'next/head'
import Image from 'next/image'
import Header from '../../../components/Header';

export default function Case() {
  return (
    <>
      <Head>
        <title>Ingsist Case</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
      </main>
    </>
  )
}
