import Head from "next/head";
import { useEffect, useRef } from "react";
import styled from "styled-components";
import Header from "@/components/Header";
import Title from "@/components/Title";
import Main from "@/components/Layout/main";
import List from "@/components/List";
import { caseItems } from "@/data/cases";
import Footer from "@/components/Footer";
import gsap from "gsap";

export default function Cases() {
  const caseRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let ctx = gsap.context(() => {
      const DELAY = 0.2;

      for (let i = 0; i < caseItems.length; i++) {
        gsap.from(`.list-item-${i}`, {
          y: 50,
          duration: 1,
          delay: i * DELAY,
          ease: "debounce",
          opacity: 0,
        });
      }
    }, caseRef);

    return () => ctx.revert();
  }, []);

  return (
    <>
      <Head>
        <title>Ingsist Cases</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={caseRef}>
        <Header />

        <Main>
          <section>
            <Title text={"Case Studies"} count={29} />

            <Ul>
              {caseItems.map((item, i) => (
                <List
                  key={item.id}
                  text={item.name}
                  year={item.year}
                  expandable={true}
                  tags={item.tag}
                  img={item.imageUrl}
                  id={item.id}
                  index={i}
                />
              ))}
            </Ul>
          </section>
        </Main>

        <Footer />
      </div>
    </>
  );
}

const Ul = styled.ul`
  margin-top: 2rem;
`;
