import Head from "next/head";
import styled from "styled-components";
import Header from "@/components/Header";
import Title from "@/components/Title";
import Main from "@/components/Layout/main";
import List from "@/components/List";
import { caseItems } from "@/data/cases";
import Footer from '@/components/Footer';

export default function Cases() {
  return (
    <>
      <Head>
        <title>Ingsist Cases</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />

        <Main>
          <section>
            <Title text={"Case Studies"} count={29} />

            <Ul>
              {caseItems.map((item, i) => (
                <List
                  key={i}
                  text={item.name}
                  year={item.year}
                  expandable={true}
                  tags={item.tag}
                  img={item.imageUrl}
                />
              ))}
            </Ul>
          </section>
        </Main>

        <Footer />
      </div>
    </>
  );
}

const Ul = styled.ul`
  margin-top: 2rem;
`;
